# syntax=docker/dockerfile:1

FROM node:16-alpine
ENV NODE_ENV=development
ENV IS_DOCKER=is_docker
ENV JWT_COOKIE_EXPIRATION=100
ENV JWT_KEY=this_is_a_non_secure_key_please_not_use_it_for_production
ENV JWT_EXPIRATION=15d
WORKDIR /src
COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm install 
COPY . .
EXPOSE 3000
CMD ["npm", "run", "start-dev" ]
