# syntax=docker/dockerfile:1

FROM node:16-alpine
ENV NODE_ENV=development, IS_DOCKER=is_docker
WORKDIR /
COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm install 
COPY . .
EXPOSE 3000
CMD ["npm", "run", "start-dev" ]
