version: "3.9"
services:
  database:
    image: mongo
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
    container_name: mongodb-composed
  
  app:
    build: 
      context: .
      dockerfile: Dockerfile-dev
    ports:  
      - 3000:3000
    container_name: codetricks
volumes:
  db:
  appsrc:

  
